name: Autograding Tests

on:
  push
  repository_dispatch

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Assignment-3 on Arrays
        id: assignment-3-on-arrays
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: Assignment-3 on Arrays
          setup-command: javac Assignment3.java
          command: |
            output=$(java Assignment3 | tr -d '[:space:]')
            expected="3784"

            if [ "$output" = "$expected" ]; then
              echo "Test Passed"
              exit 0
            else
              echo "Test Failed"
              echo "Expected: 3 7 8 4"
              echo "Got:"
              java Assignment3
              exit 1
            fi
          timeout: 15
          max-score: 10

      - name: Autograding Reporter
        uses: classroom-resources/autograding-grading-reporter@v1
        env:
          ASSIGNMENT-3-ON-ARRAYS_RESULTS: "${{steps.assignment-3-on-arrays.outputs.result}}"
        with:
          runners: assignment-3-on-arrays